version: '3'

services:
  postgres:
    image: postgres:15
    container_name: thesaurus-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thesaurus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - thesaurus-network

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: thesaurus-meilisearch-dev
    environment:
      MEILI_MASTER_KEY: dev_master_key
      MEILI_NO_ANALYTICS: true
      MEILI_ENV: development
    volumes:
      - meilisearch-data:/meili_data/data.ms
    ports:
      - "7700:7700"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --spider http://127.0.0.1:7700/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - thesaurus-network

  thesaurus-api:
    build:
      context: ./thesaurus-api
      dockerfile: ./Dockerfile.dev
    container_name: thesaurus-api-dev
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/thesaurus
      MEILI_URL: http://meilisearch:7700
      MEILI_MASTER_KEY: dev_master_key
      JWT_SECRET: development_jwt_secret_key
      JWT_EXPIRES_IN: 60
      JWT_MAXAGE: 60
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    volumes:
      - ./thesaurus-api:/app
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target:/app/target
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    networks:
      - thesaurus-network
    command: cargo watch -x run

  pgadmin:
    image: dpage/pgadmin4
    container_name: thesaurus-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - thesaurus-network

volumes:
  postgres-data:
  meilisearch-data:
  cargo-registry:
  cargo-git:
  target:

networks:
  thesaurus-network:
    driver: bridge